### ISSUE TITLE
Getting started: start failed!

### ISSUE THREAD

**Issue by XuTpuK** [buggins/dlangui#130]
In the very first try user will fail trying to run even simplistic app! In "Getting Started" we try to build library and get this:
    C:\Users\...\dub\packages\dlangui-master\src\dlangui\core\files.d(264,22): Error: cannot implicitly convert expression (lastSlash + 1LU) of type ulong to uint
    C:\Users\...\dub\packages\dlangui-master\src\dlangui\core\files.d(354,17): Error: cannot implicitly convert expression (start) of type ulong to uint

OK, no problem to fix unnecessary ulong type and put uint. But when we try to use Button with handler:

    // assign Ok button onClick handler: show content of editor
    btn1.onClickListener = delegate(Widget src) {
        window.showMessageBox("Button btn1 pressed"d, "Editor content:"d ~ edit1.text);
        return true;
    };

....we get smashed by absolutely stupid error:

    Error: no property 'onClickListener' for type 'dlangui.widgets.controls.Button'

And this is FIRST experience user get from dlangui?! No way, man!

**Comment by sigod** [comment]
> C:\Users...\dub\packages\dlangui-master\src\dlangui\core\files.d(264,22): Error: cannot implicitly convert expression (lastSlash + 1LU) of type ulong to uint
> C:\Users...\dub\packages\dlangui-master\src\dlangui\core\files.d(354,17): Error: cannot implicitly convert expression (start) of type ulong to uint

Are you on x86 system? Looks like it might have been caused by #128 PR.

**Comment by XuTpuK** [comment]
I'm on Win7 x64. It's strange to use so huge type to address file path! (and nobody got compile error??)

**Comment by sigod** [comment]
Just tried and got the same compile errors for v0.7.29 and v0.7.28.

v0.7.27 compiles without problems.

**Comment by g4z3r** [comment]
Sorry, my fault with types, I don't work on Windows.
`onClickListener` is an old name, use `click` instead. Need to update docs accordingly.

**Comment by buggins** [comment]
Many of signal names were changed to shorter ones.
Need to update documentation.
Where is Getting Started doc located?

**Comment by g4z3r** [comment]
https://github.com/buggins/dlangui/wiki/Getting-Started

**Comment by buggins** [comment]
Fixed both Wiki and dlangui-examples code,
